/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Define the RCC clock configuration register */
#define RCC_BASE_ADDR (0x40023800UL)
#define RCC_CFRG_REG_OFFSET (0x08UL)
#define RCC_CR_REG_OFFSET (0x00UL)
#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET )
#define RCC_CR_REG_ADDR (RCC_BASE_ADDR + RCC_CR_REG_OFFSET )

/* Define the GPIOA register */
#define GPIOA_BASE_ADDR (0x40020000UL)

int main(void)
{
	/* Initialize register addresses */
	uint32_t *pRccCrReg = (uint32_t*) RCC_CFGR_REG_ADDR;
	uint32_t *pRccCfgrReg = (uint32_t) RCC_CFGR_REG_ADDR;
	uint32_t *pRCCAhb1Enr = (uint32_t*)(RCC_BASE_ADDR + 0x30);
	uint32_t *pGPIOAModeReg = (uint32_t*)(GPIOA_BASE_ADDR + 00);
	uint32_t *pGPIOAAltFunHighReg = (uint32_t*)(GPIOA_BASE_ADDR + 0x24);


	/* Enable the HSE clock using HSEON bit */
	*pRccCrReg |= (1 << 16);

	/*
	 * Wait until HSE clock from the external crystal
	 * stabilizes (only if crystal is connected)
	*/
	while(!(*pRccCrReg & (1 << 17)));

	/* Switch the system clock to HSE (RCC_CFGR) */
	*pRccCfgrReg |= (1 << 0);

	/* Configure the RCC_CFGR MCO1 bit fields to select HSE as clock source */
	*pRccCfgrReg |= ( 1 << 22); //clear 21 and SET 22

	/* Configure MCO1 pre-scaler, use 4 as divisor */
	*pRccCfgrReg |= ( 1 << 25);
	*pRccCfgrReg |= ( 1 << 26);

	/* Configure PA8 to AF0 mode to behave as MCO1 signal */

	/* Enable the peripheral clock for GPIOA peripheral */
	*pRCCAhb1Enr |= (1 << 0); //Enable GPIOA peripheral clock

	/* Configure the mode of GPIOA pin 8 as alternate function mode */
	*pGPIOAModeReg &= ~(0x3 << 16); // Clear
	*pGPIOAModeReg |= (0x2 << 16);  // Set

	/* Configure the alternation function register to set the mode 0 for PA8 */
	*pGPIOAAltFunHighReg &= ~(0xF << 0);

    /* Loop forever */
	for(;;);
}
