/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Define the RCC clock configuration register */
#define RCC_BASE_ADDR (0x40023800UL)
#define RCC_CFRG_REG_OFFSET (0x08UL)
#define RCC_CR_REG_OFFSET (0x00UL)
#define RCC_CFGR_REG_ADDR (RCC_BASE_ADDR + RCC_CFGR_REG_OFFSET )
#define RCC_CR_REG_ADDR (RCC_BASE_ADDR + RCC_CR_REG_OFFSET )

/* Define the GPIOA register */
#define GPIOA_BASE_ADDR (0x40020000UL)

int main(void)
{

    /* Loop forever */
	for(;;);
}
